"""Avila–Viana inspired pinching / twisting diagnostics for the Prym pipeline.

These are practical numerical (and exact-arithmetic ready) tests that can be
applied to any finite set of transition matrices. They do not prove simplicity
of a genuine spectrum; they strengthen the linear-model scaffold and become
decisive once a Prym-compatible Rauzy class is available.

Key functions:
- singular_value_gaps / is_pinching : numerical pinching proxy
- twisting_sample_fraction : Monte-Carlo transversality proxy
- monoid_pinching_score : sample the monoid generated by a list of matrices
"""
from __future__ import annotations
import numpy as np
from typing import List, Dict, Tuple, Optional

def singular_values(A: np.ndarray) -> np.ndarray:
    return np.linalg.svd(A, compute_uv=False)

def singular_value_gaps(A: np.ndarray, tol: float = 1e-12) -> np.ndarray:
    s = np.maximum(singular_values(A), tol)
    return s[:-1] / s[1:]

def is_pinching(A: np.ndarray, min_gap: float = 10.0) -> Tuple[bool, float]:
    gaps = singular_value_gaps(A)
    max_gap = float(np.max(gaps)) if len(gaps) else 0.0
    return max_gap >= min_gap, max_gap

def eigenvalue_moduli_gaps(A: np.ndarray) -> np.ndarray:
    ev = np.linalg.eigvals(A)
    mods = np.sort(np.abs(ev))[::-1]
    mods = np.maximum(mods, 1e-15)
    return mods[:-1] / mods[1:]

def is_transverse(v: np.ndarray, W: np.ndarray, tol: float = 1e-8) -> bool:
    # residual of v after projection onto columns of W
    if W.size == 0:
        return True
    q, _ = np.linalg.qr(W)
    proj = q @ (q.T @ v)
    return float(np.linalg.norm(v - proj)) > tol

def twisting_sample_fraction(B: np.ndarray, n_samples: int = 40, k: int = 1, seed: int = 0) -> float:
    rng = np.random.default_rng(seed)
    dim = B.shape[0]
    count = 0
    for _ in range(n_samples):
        M = rng.standard_normal((dim, k))
        q, _ = np.linalg.qr(M)
        F = q[:, :k]
        BF = B @ F
        # complementary random plane
        M2 = rng.standard_normal((dim, dim - k))
        q2, _ = np.linalg.qr(M2)
        W = q2[:, :dim-k]
        if is_transverse(BF.ravel() if k == 1 else BF, W):
            count += 1
    return count / n_samples

def monoid_pinching_score(gens: Dict[str, np.ndarray], max_len: int = 3, n_random: int = 50, min_gap: float = 5.0, seed: int = 1) -> Dict:
    rng = np.random.default_rng(seed)
    names = list(gens.keys())
    mats = list(gens.values())
    dim = mats[0].shape[0]
    pinching = 0
    max_gap_seen = 0.0
    for _ in range(n_random):
        length = rng.integers(1, max_len + 1)
        idx = rng.integers(0, len(mats), size=length)
        M = np.eye(dim)
        for i in idx:
            M = mats[i] @ M
        ok, gap = is_pinching(M, min_gap=min_gap)
        if ok:
            pinching += 1
        max_gap_seen = max(max_gap_seen, gap)
    return {
        "n_trials": n_random,
        "n_pinching": pinching,
        "fraction_pinching": pinching / n_random if n_random else 0.0,
        "max_gap_seen": max_gap_seen if np.isfinite(max_gap_seen) else "Infinity",
    }

def diagnose_monoid(gens: Dict[str, np.ndarray], max_len: int = 2, min_gap: float = 5.0) -> Dict:
    score = monoid_pinching_score(gens, max_len=max_len, min_gap=min_gap)
    # also test elementary generators
    elem = {n: is_pinching(M, min_gap=min_gap) for n, M in gens.items()}
    return {
        "elementary_pinching": elem,
        "monoid_score": score,
        "note": "Numerical proxies only. Full Avila–Viana criterion requires exact pinching and rigorous twisting on isotropic Grassmannians.",
    }
